parameters:

services:

    pgs.core.twig.time_ago:
        class: "PGS\CoreDomainBundle\Twig\TimeAgoExtension"
        arguments: [@translator]
        tags:
        - { name: twig.extension }

    pgs.core.extension.active_preference:
        class: "PGS\CoreDomainBundle\Twig\ActivePreferenceExtension"
        arguments:
            - @pgs.core.container.active_preference
        tags:
            - { name: twig.extension }
