<?php

namespace PGS\CoreDomainBundle\Model\SchoolClassCourseStudentBehavior;

use PGS\CoreDomainBundle\Model\SchoolClassCourseStudentBehavior\om\BaseSchoolClassCourseStudentBehaviorPeer;

class SchoolClassCourseStudentBehaviorPeer extends BaseSchoolClassCourseStudentBehaviorPeer
{
}
