pgs_core_avatar_list:
    pattern:  /avatar-list
    defaults: { _controller: PGSCoreDomainBundle:Avatar:list}
    requirements:
        _method: GET

pgs_core_avatar_new:
    pattern:  /new-avatar
    defaults: { _controller: PGSCoreDomainBundle:Avatar:new}
    requirements:
        _method: GET|POST

pgs_core_avatar_edit:
    pattern:  /edit-avatar
    defaults: { _controller: PGSCoreDomainBundle:Avatar:edit}
    requirements:
        _method: GET|POST

pgs_core_avatar_delete:
    pattern:  /delete-avatar
    defaults: { _controller: PGSCoreDomainBundle:Avatar:delete}
    requirements:
        _method: GET

pgs_core_avatar_view:
    pattern:  /view-avatar
    defaults: { _controller: PGSCoreDomainBundle:Avatar:view}
    requirements:
        _method: GET

pgs_core_avatar_upload:
    pattern: /upload/{id}
    defaults: { _controller: PGSCoreDomainBundle:Avatar:upload, id: null }