pgs_core_formula_list:
    pattern:  /
    defaults: { _controller: PGSCoreDomainBundle:Formula:list }
    requirements:
        _method: GET

pgs_core_formula_view:
    pattern:  /view/{id}
    defaults: { _controller: PGSCoreDomainBundle:Formula:view, id: null }
    requirements:
        _method: GET

pgs_core_formula_new:
    pattern:  /new
    defaults: { _controller: PGSCoreDomainBundle:Formula:new }
    requirements:
        _method: GET|POST

pgs_core_formula_edit:
    pattern:  /edit/{id}
    defaults: { _controller: PGSCoreDomainBundle:Formula:edit, id: null }
    requirements:
        _method: GET|POST

pgs_core_formula_delete:
    pattern:  /delete/{id}
    defaults: { _controller: PGSCoreDomainBundle:Formula:delete, id: null }
    requirements:
        _method: GET|POST
