pgs_core_level_list:
    pattern:  /
    defaults: { _controller: PGSCoreDomainBundle:Level:list }
    requirements:
        _method: GET

pgs_core_level_view:
    pattern:  /view/{id}
    defaults: { _controller: PGSCoreDomainBundle:Level:view, id: null }
    requirements:
        _method: GET

pgs_core_level_new:
    pattern:  /new
    defaults: { _controller: PGSCoreDomainBundle:Level:new }
    requirements:
        _method: GET|POST

pgs_core_level_edit:
    pattern:  /edit/{id}
    defaults: { _controller: PGSCoreDomainBundle:Level:edit, id: null }
    requirements:
        _method: GET|POST

pgs_core_level_delete:
    pattern:  /delete/{id}
    defaults: { _controller: PGSCoreDomainBundle:Level:delete, id: null }
    requirements:
        _method: GET|POST
