pgs_core_medical_list:
    pattern:  /
    defaults: { _controller: PGSCoreDomainBundle:Medical:list }
    requirements:
        _method: GET

pgs_core_medical_view:
    pattern:  /view/{id}
    defaults: { _controller: PGSCoreDomainBundle:Medical:view, id: null }
    requirements:
        _method: GET

pgs_core_medical_new:
    pattern:  /new
    defaults: { _controller: PGSCoreDomainBundle:Medical:new }
    requirements:
        _method: GET|POST

pgs_core_medical_edit:
    pattern:  /edit/{id}
    defaults: { _controller: PGSCoreDomainBundle:Medical:edit, id: null }
    requirements:
        _method: GET|POST

pgs_core_medical_delete:
    pattern:  /delete/{id}
    defaults: { _controller: PGSCoreDomainBundle:Medical:delete, id: null }
    requirements:
        _method: GET|POST