pgs_core_parent_student_list:
    pattern:  /
    defaults: { _controller: PGSCoreDomainBundle:ParentStudent:list }
    requirements:
        _method: GET

pgs_core_parent_student_view:
    pattern:  /view/{id}
    defaults: { _controller: PGSCoreDomainBundle:ParentStudent:view, id: null }
    requirements:
        _method: GET

#pgs_core_parent_student_new:
#    pattern:  /new/{parent}
#    defaults: { _controller: PGSCoreDomainBundle:ParentStudent:new, parent: null }
#    requirements:
#        _method: GET|POST

pgs_core_parent_student_edit:
    pattern:  /edit/{id}
    defaults: { _controller: PGSCoreDomainBundle:ParentStudent:edit, id: null }
    requirements:
        _method: GET|POST

pgs_core_parent_student_delete:
    pattern:  /delete/{id}
    defaults: { _controller: PGSCoreDomainBundle:ParentStudent:delete, id: null }
    requirements:
        _method: GET|POST

pgs_core_parent_student_activate:
    pattern:  /activate/{id}
    defaults: { _controller: PGSCoreDomainBundle:ParentStudent:activate, id: null }
    requirements:
        _method: GET|POST
