pgs_core_school_grade_level_list:
    pattern:  /
    defaults: { _controller: PGSCoreDomainBundle:SchoolGradeLevel:list }
    requirements:
        _method: GET

pgs_core_school_grade_level_view:
    pattern:  /view/{id}
    defaults: { _controller: PGSCoreDomainBundle:SchoolGradeLevel:view, id: null }
    requirements:
        _method: GET

pgs_core_school_grade_level_new:
    pattern:  /new/{parent}
    defaults: { _controller: PGSCoreDomainBundle:SchoolGradeLevel:new, parent: null }
    requirements:
        _method: GET|POST

pgs_core_school_grade_level_edit:
    pattern:  /edit/{id}
    defaults: { _controller: PGSCoreDomainBundle:SchoolGradeLevel:edit, id: null }
    requirements:
        _method: GET|POST

pgs_core_school_grade_level_delete:
    pattern:  /delete/{id}
    defaults: { _controller: PGSCoreDomainBundle:SchoolGradeLevel:delete, id: null }
    requirements:
        _method: GET|POST

pgs_core_school_grade_level_by_access:
    pattern: /list/access/{access}
    defaults: { _controller: PGSCoreDomainBundle:SchoolGradeLevel:viewSchoolGradeLevelByAccess, access: all }

pgs_core_school_grade_level_activate:
    pattern:  /activate/{id}
    defaults: { _controller: PGSCoreDomainBundle:SchoolGradeLevel:activate, id: null }
    requirements:
        _method: GET|POST

pgs_core_school_grade_level_move:
    pattern:  /move/{id}/{direction}
    defaults: { _controller: PGSCoreDomainBundle:SchoolGradeLevel:move, id:null, direction: null }
    requirements:
        _method: GET|POST
