pgs_core_school_class_list:
    pattern:  /
    defaults: { _controller: PGSCoreDomainBundle:SchoolClass:list }
    requirements:
        _method: GET

pgs_core_school_class_view:
    pattern:  /view/{id}
    defaults: { _controller: PGSCoreDomainBundle:SchoolClass:view, id: null }
    requirements:
        _method: GET

pgs_core_school_class_new:
    pattern:  /new/{parent}
    defaults: { _controller: PGSCoreDomainBundle:SchoolClass:new, parent: null }
    requirements:
        _method: GET|POST

pgs_core_school_class_edit:
    pattern:  /edit/{id}
    defaults: { _controller: PGSCoreDomainBundle:SchoolClass:edit, id: null }
    requirements:
        _method: GET|POST

pgs_core_school_class_delete:
    pattern:  /delete/{id}
    defaults: { _controller: PGSCoreDomainBundle:SchoolClass:delete, id: null }
    requirements:
        _method: GET|POST

pgs_core_school_class_by_status:
    pattern: /list/status/{status}
    defaults: { _controller: PGSCoreDomainBundle:SchoolClass:viewSchoolClassByStatus, status: all }

pgs_core_school_class_move:
    pattern:  /move/{id}/{direction}
    defaults: { _controller: PGSCoreDomainBundle:SchoolClass:move, id:null, direction: null }
    requirements:
        _method: GET|POST

pgs_core_school_class_upload:
    pattern: /upload/{id}
    defaults: { _controller: PGSCoreDomainBundle:SchoolClass:upload, id: null }
