pgs_core_student_medical_list:
    pattern:  /
    defaults: { _controller: PGSCoreDomainBundle:StudentMedical:list }
    requirements:
        _method: GET

pgs_core_student_medical_view:
    pattern:  /view/{schoolHealthId}
    defaults: { _controller: PGSCoreDomainBundle:StudentMedical:view, schoolHealthId: null }
    requirements:
        _method: GET

#pgs_core_student_medical_new:
#    pattern:  /new/{schoolHealthId}
#    defaults: { _controller: PGSCoreDomainBundle:StudentMedical:new,  schoolHealthId: null }
#    requirements:
#        _method: GET|POST
#
#pgs_core_student_medical_edit:
#    pattern:  /edit/{id}
#    defaults: { _controller: PGSCoreDomainBundle:StudentMedical:edit, id: null }
#    requirements:
#        _method: GET|POST
#
#pgs_core_student_medical_delete:
#    pattern:  /delete/{id}
#    defaults: { _controller: PGSCoreDomainBundle:StudentMedical:delete, id: null }
#    requirements:
#        _method: GET|POST

pgs_core_student_medical_fetch:
    pattern:  /fetch/{random}/{schoolHealthId}
    defaults: { _controller: PGSCoreDomainBundle:StudentMedical:fetchRecord, random : null, schoolHealthId: null }
    requirements:
        _method: GET|POST