pgs_core_student_list:
    pattern:  /
    defaults: { _controller: PGSCoreDomainBundle:Student:list }
    requirements:
        _method: GET

pgs_core_student_view:
    pattern:  /view/{id}
    defaults: { _controller: PGSCoreDomainBundle:Student:view, id: null }
    requirements:
        _method: GET

pgs_core_student_new:
    pattern:  /new/{parent}
    defaults: { _controller: PGSCoreDomainBundle:Student:new, parent: null }
    requirements:
        _method: GET|POST

pgs_core_student_edit:
    pattern:  /edit/{id}
    defaults: { _controller: PGSCoreDomainBundle:Student:edit, id: null }
    requirements:
        _method: GET|POST

pgs_core_student_delete:
    pattern:  /delete/{id}
    defaults: { _controller: PGSCoreDomainBundle:Student:delete, id: null }
    requirements:
        _method: GET|POST

pgs_core_student_activate:
    pattern:  /activate/{id}
    defaults: { _controller: PGSCoreDomainBundle:Student:activate, id: null }
    requirements:
        _method: GET|POST
