pgs_core_topic_list:
    pattern:  /
    defaults: { _controller: PGSCoreDomainBundle:Topic:list }
    requirements:
        _method: GET

pgs_core_topic_view:
    pattern:  /view/{id}
    defaults: { _controller: PGSCoreDomainBundle:Topic:view, id: null }
    requirements:
        _method: GET

pgs_core_topic_new:
    pattern:  /new/{parent}
    defaults: { _controller: PGSCoreDomainBundle:Topic:new, parent: null }
    requirements:
        _method: GET|POST

pgs_core_topic_edit:
    pattern:  /edit/{id}
    defaults: { _controller: PGSCoreDomainBundle:Topic:edit, id: null }
    requirements:
        _method: GET|POST

pgs_core_topic_delete:
    pattern:  /delete/{id}
    defaults: { _controller: PGSCoreDomainBundle:Topic:delete, id: null }
    requirements:
        _method: GET|POST

pgs_core_topic_by_access:
    pattern: /list/access/{access}
    defaults: { _controller: PGSCoreDomainBundle:Topic:viewTopicByAccess, access: all }

pgs_core_topic_move:
    pattern:  /move/{id}/{direction}
    defaults: { _controller: PGSCoreDomainBundle:Topic:move, id:null, direction: null }
    requirements:
        _method: GET|POST
