# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_PRINCIPAL:     [ROLE_USER, ROLE_PRINCIPAL]
        ROLE_SALES:         [ROLE_USER, ROLE_SALES]
        ROLE_OFFICE:        [ROLE_USER, ROLE_OFFICE, ROLE_SALES, ROLE_PRINCIPAL]
        ROLE_ADMIN:         [ROLE_USER, ROLE_ADMIN, ROLE_OFFICE, ROLE_SALES, ROLE_PRINCIPAL]
        ROLE_SUPER_ADMIN:   [ROLE_PGS, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: pgs.core.security.user_provider

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                success_handler: pgs.core.security.authentication_handler
            logout: true
            anonymous:    true

    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login_check, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/super_admin, role: ROLE_SUPER_ADMIN }
        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/office, role: ROLE_OFFICE }
        - { path: ^/principal, role: ROLE_PRINCIPAL }
        - { path: ^/sales, role: ROLE_SALES }
        - { path: ^/user/office, role: ROLE_OFFICE }
        - { path: ^/user/principal, role: ROLE_PRINCIPAL }
        - { path: ^/user/sales, role: ROLE_SALES }
        - { path: ^/user/, role: ROLE_USER }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
