# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_APPLICANT:     [ROLE_USER, ROLE_APPLICANT]
        ROLE_STUDENT:       [ROLE_USER, ROLE_STUDENT]
        ROLE_PARENT:        [ROLE_USER, ROLE_PARENT]
        ROLE_TEACHER:       [ROLE_USER, ROLE_TEACHER]
        ROLE_COUNSELOR:     [ROLE_USER, ROLE_COUNSELOR, ROLE_TEACHER, ROLE_STUDENT]
        ROLE_PRINCIPAL:     [ROLE_USER, ROLE_PRINCIPAL, ROLE_COUNSELOR, ROLE_TEACHER, ROLE_STUDENT]
        ROLE_SCHOOL:        [ROLE_USER, ROLE_SCHOOL, ROLE_PRINCIPAL, ROLE_COUNSELOR, ROLE_TEACHER, ROLE_STUDENT]
        ROLE_ADMIN:         [ROLE_USER, ROLE_ADMIN, ROLE_SCHOOL, ROLE_PRINCIPAL, ROLE_COUNSELOR, ROLE_TEACHER, ROLE_STUDENT, ROLE_PARENT]
        ROLE_SUPER_ADMIN:   [ROLE_PGS, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: pgs.core.security.user_provider

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                success_handler: pgs.core.security.authentication_handler
            logout: true
            anonymous:    true

    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login_check, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/applicant, role: ROLE_APPLICANT }
        - { path: ^/schooladmin, role: ROLE_SCHOOL }
        - { path: ^/super_admin, role: ROLE_SUPER_ADMIN }
        - { path: ^/student, role: ROLE_STUDENT }
        - { path: ^/parent, role: ROLE_PARENT }
        - { path: ^/teacher, role: ROLE_TEACHER }
        - { path: ^/couselor, role: ROLE_COUNSELOR }
        - { path: ^/principal, role: ROLE_PRINCIPAL }
        - { path: ^/user/student, role: ROLE_STUDENT }
        - { path: ^/user/parent, role: ROLE_PARENT }
        - { path: ^/user/teacher, role: ROLE_TEACHER }
        - { path: ^/user/couselor, role: ROLE_COUNSELOR }
        - { path: ^/user/principal, role: ROLE_PRINCIPAL }
        - { path: ^/user/, role: ROLE_USER }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
