pgs_hms:
    pgs_title: ClassGizmo
    pgs_debug: false
    pgs_page_number: 10

#    templates:
#        base:           PGSWebBundle::base.html.twig
#        ajax:           PGSWebBundle::ajax.html.twig
#        dashboard:      PGSWebBundle:::dashboard.html.twig
#        layout:         PGSWebBundle::layout.html.twig
#        menuMain:       PGSWebBundle::menuMain.html.twig
#        menuBottom:     PGSWebBundle::menuBottom.html.twig
#        menuContext:    PGSWebBundle::menuContext.html.twig
#
#        # default value if done set, actions templates, should extend global templates
#        list:    ~ #PGSWebBundle:CRUD:list.html.twig
#        show:    ~ #PGSWebBundle:CRUD:show.html.twig
#        edit:    ~ #PGSWebBundle:CRUD:edit.html.twig

