sonata_block:
    default_contexts: [cms]
    blocks:
        # Enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts:   [admin]

        #sonata.admin_doctrine_orm.block.audit:
        #    contexts:   [admin]

        sonata.block.service.text:
        sonata.block.service.action:
        sonata.block.service.rss:

        # Some specific block from the SonataMediaBundle
#        sonata.media.block.media:
#        sonata.media.block.gallery:
#        sonata.media.block.feature_media:

sonata_admin:
    title:  Protouch Global Solutions
    title_logo: /bundles/Protouch.png
    dashboard:
        blocks:
            -
                position: left
                type: sonata.admin.block.admin_list
            -
                position: right
                type: sonata.block.service.text
                settings:
                    content: >
                        <h2>Protouch Global Solutions - Administration</h2>
                        <h3>Admin Panel</h3>
            -
                position: right
                type: sonata.block.service.rss
                settings:
                    title: Protouch Global Solutions Feeds
                    url: http://protouchconsulting.com
    templates:
        dashboard: SonataAdminBundle:Core:dashboard.html.twig
#        layout:  PGSHotelManagementBundle:Sonata:standard_layout.html.twig
        ajax:    SonataAdminBundle::ajax_layout.html.twig

        # default value if done set, actions templates, should extend global templates
        list:    SonataAdminBundle:CRUD:list.html.twig
        show:    SonataAdminBundle:CRUD:show.html.twig
#        edit:    PGSHotelManagementBundle:Sonata:crudedit.html.twig

    options:
        use_select2:  true
#    security:
#        handler: sonata.admin.security.handler.role
#        acl_user_manager: fos_user.user_manager # Name of the user manager service used to retrieve ACL users

#    options:
#        html5_validate: false # does not use html5 validation
#        confirm_exit:   false # disable confirmation when quitting with unsaved changes
#        pager_links:    5     # pager max links to display
#
#    # set to true to persist filter settings per admin module in the user's session
#    persist_filters: false

#sonata_propel_orm_admin:
#    templates:
#        types:
#            list:
#                array:      SonataAdminBundle:CRUD:list_array.html.twig
#                boolean:    SonataAdminBundle:CRUD:list_boolean.html.twig
#                date:       SonataAdminBundle:CRUD:list_date.html.twig
#                time:       SonataAdminBundle:CRUD:list_time.html.twig
#                datetime:   SonataAdminBundle:CRUD:list_datetime.html.twig
#                text:       SonataAdminBundle:CRUD:list_string.html.twig
#                trans:      SonataAdminBundle:CRUD:list_trans.html.twig
#                string:     SonataAdminBundle:CRUD:list_string.html.twig
#                smallint:   SonataAdminBundle:CRUD:list_string.html.twig
#                bigint:     SonataAdminBundle:CRUD:list_string.html.twig
#                integer:    SonataAdminBundle:CRUD:list_string.html.twig
#                decimal:    SonataAdminBundle:CRUD:list_string.html.twig
#                identifier: SonataAdminBundle:CRUD:list_string.html.twig
#                currency:   SonataAdminBundle:CRUD:list_currency.html.twig
#                percent:    SonataAdminBundle:CRUD:list_percent.html.twig
#
#            show:
#                array:      SonataAdminBundle:CRUD:show_array.html.twig
#                boolean:    SonataAdminBundle:CRUD:show_boolean.html.twig
#                date:       SonataAdminBundle:CRUD:show_date.html.twig
#                time:       SonataAdminBundle:CRUD:show_time.html.twig
#                datetime:   SonataAdminBundle:CRUD:show_datetime.html.twig
#                text:       SonataAdminBundle:CRUD:base_show_field.html.twig
#                trans:      SonataAdminBundle:CRUD:show_trans.html.twig
#                string:     SonataAdminBundle:CRUD:base_show_field.html.twig
#                smallint:   SonataAdminBundle:CRUD:base_show_field.html.twig
#                bigint:     SonataAdminBundle:CRUD:base_show_field.html.twig
#                integer:    SonataAdminBundle:CRUD:base_show_field.html.twig
#                decimal:    SonataAdminBundle:CRUD:base_show_field.html.twig
#                currency:   SonataAdminBundle:CRUD:base_currency.html.twig
#                percent:    SonataAdminBundle:CRUD:base_percent.html.twig
